# Generated by Django 3.2.6 on 2021-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerquestion',
            name='new_answer',
            field=models.TextField(null=True, verbose_name='текст своего ответа'),
        ),
    ]
