# Generated by Django 3.2.6 on 2021-08-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('start_date', models.DateTimeField(editable=False, verbose_name='дата старта')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'polls_db',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('type', models.CharField(choices=[('TEXT', 'Ответ текстом'), ('ONE_CHOICE', 'Ответ с выбором одного варианта'), ('MULTIPLE_CHOICE', 'Ответ с выбором нескольких вариантов')], default='TEXT', max_length=30)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question_db',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer_db',
                'ordering': ['id'],
            },
        ),
    ]
